### PR TITLE
EZP-28161: Update php-cs-fixer configuration to align with v2.7.1

### PR DESCRIPTION
**Pull request by alongosz**
# Fixes [EZP-28161](https://jira.ez.no/browse/EZP-28161)

This PR aligns php-cs-fixer settings with v2.7.1 and conventions accepted in other repositories.

To simplify fixing code it adds dependency on `php-cs-fixer` and introduces composer command:
```
composer fix-cs
```
which runs fixer on all files.

**TODO**:
- [x] Rename `.php_cs.dist` to `.php_cs`
- [x] Update php-cs-fixer config (`.php_cs`)
- [x] Add `php-cs-fixer` dev dependency to composer pointing to `~2.7.1`
- [x] Add composer command `fix-cs`
- [x] Create test matrix to be able to set env variable per job
- [x] Test on PHP `7.2`
- [x] Create prototype for running php-cs-fixer on Travis
- [x] Remove TMP commit

### CODE REVIEW

**Comment by alongosz** [comment]
Looks like ezrobot doesn't check CS here. @andrerom @vidarl should we keep it like that?

**Comment by andrerom** [comment]
Could optionally get travis to do it here.

**Comment by alongosz** [comment]
I've introduced test matrix based on what we have in kernel, so I can control which script to execute by env vars.
I've also added testing on `7.1`. 
`7.1` job runs both `phpunit` and `php-cs-fixer` to save Travis resources and time.

Look at this pretty fail: https://travis-ci.org/ezsystems/ezplatform-design-engine/jobs/299111395#L643-L671 :grinning: // also cc @adamwojs 

Now let's see if it doesn't fail when CS is ok...

**Comment by alongosz** [comment]
Prototype CS fixer on Travis works :) 

It is fine for this small package. For bigger ones requires some tweaks, like checking only added and modified files and displaying fixer output in some more visible manner (would like to try in the future making automated PR review).

So this is ready for a final review @andrerom @adamwojs @lserwatka

**Pull request merged**
