### PR TITLE
Added TestCase instead of non namespaced PHPUnit_Framework_TestCase

### PR DESCRIPTION
**Pull request by MarioBlazek**

### CODE REVIEW

**Comment by lolautruche** [comment]
@MarioBlazek Aren't namespaces introduced only in PHPUnit 6?

**Comment by MarioBlazek** [comment]
Yes, namespaces are introduced in v6. This is provided by phpunit as forward compatibility layer.

**Comment by lolautruche** [comment]
How is it provided by PHPUnit 5.7? With the `class_alias()` trick like Twig?

**Comment by MarioBlazek** [comment]
I think `class_alias()` is in question.

**Comment by MarioBlazek** [comment]
It was added in 5.4 https://github.com/sebastianbergmann/phpunit/blob/5.4/ChangeLog-5.4.md#540---2016-06-03

**Comment by lolautruche** [comment]
ok

**Pull request merged**
